//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace School.Common.Core {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("School.Common.Core.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All students.
        /// </summary>
        public static string AllStudents {
            get {
                return ResourceManager.GetString("AllStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All students assigned to the {0}.
        /// </summary>
        public static string AllStudentsAssignedToTheTeacherFormat {
            get {
                return ResourceManager.GetString("AllStudentsAssignedToTheTeacherFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All teachers.
        /// </summary>
        public static string AllTeachers {
            get {
                return ResourceManager.GetString("AllTeachers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All teachers with assigned students.
        /// </summary>
        public static string AllTeachersWithAssignedStudents {
            get {
                return ResourceManager.GetString("AllTeachersWithAssignedStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds new student to the database.
        /// </summary>
        public static string CommandDescription_AddStudent {
            get {
                return ResourceManager.GetString("CommandDescription_AddStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds new teacher to the database.
        /// </summary>
        public static string CommandDescription_AddTeacher {
            get {
                return ResourceManager.GetString("CommandDescription_AddTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigns teacher to a student.
        /// </summary>
        public static string CommandDescription_AssignTeacher {
            get {
                return ResourceManager.GetString("CommandDescription_AssignTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clears the console window of display information.
        /// </summary>
        public static string CommandDescription_Clear {
            get {
                return ResourceManager.GetString("CommandDescription_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes student from the database.
        /// </summary>
        public static string CommandDescription_DelStudent {
            get {
                return ResourceManager.GetString("CommandDescription_DelStudent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deletes teacher from the database.
        /// </summary>
        public static string CommandDescription_DelTeacher {
            get {
                return ResourceManager.GetString("CommandDescription_DelTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quits the application.
        /// </summary>
        public static string CommandDescription_Exit {
            get {
                return ResourceManager.GetString("CommandDescription_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows all available commands.
        /// </summary>
        public static string CommandDescription_Help {
            get {
                return ResourceManager.GetString("CommandDescription_Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prints students list with its teachers.
        /// </summary>
        public static string CommandDescription_PrintStudents {
            get {
                return ResourceManager.GetString("CommandDescription_PrintStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prints teachers list with all their students.
        /// </summary>
        public static string CommandDescription_PrintTeachers {
            get {
                return ResourceManager.GetString("CommandDescription_PrintTeachers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revokes teacher from the student.
        /// </summary>
        public static string CommandDescription_RevokeTeacher {
            get {
                return ResourceManager.GetString("CommandDescription_RevokeTeacher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command does not exist. Type &quot;help&quot; to see commans list.
        /// </summary>
        public static string CommandDoesNotExist {
            get {
                return ResourceManager.GetString("CommandDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0,-15}{1}.
        /// </summary>
        public static string CommandFormat {
            get {
                return ResourceManager.GetString("CommandFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter students age (integer).
        /// </summary>
        public static string EnterStudentsAge {
            get {
                return ResourceManager.GetString("EnterStudentsAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter students firts name.
        /// </summary>
        public static string EnterStudentsFirtsName {
            get {
                return ResourceManager.GetString("EnterStudentsFirtsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter students last name.
        /// </summary>
        public static string EnterStudentsLastName {
            get {
                return ResourceManager.GetString("EnterStudentsLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter teachers age (integer).
        /// </summary>
        public static string EnterTeachersAge {
            get {
                return ResourceManager.GetString("EnterTeachersAge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter teachers firts name.
        /// </summary>
        public static string EnterTeachersFirtsName {
            get {
                return ResourceManager.GetString("EnterTeachersFirtsName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter teachers last name.
        /// </summary>
        public static string EnterTeachersLastName {
            get {
                return ResourceManager.GetString("EnterTeachersLastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Age value. It should be integer.
        /// </summary>
        public static string InvalidAgeValue {
            get {
                return ResourceManager.GetString("InvalidAgeValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Id. It should be integer.
        /// </summary>
        public static string InvalidId {
            get {
                return ResourceManager.GetString("InvalidId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to     {0}.
        /// </summary>
        public static string NestedElementFormat {
            get {
                return ResourceManager.GetString("NestedElementFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Students.
        /// </summary>
        public static string NoStudents {
            get {
                return ResourceManager.GetString("NoStudents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No students to assign.
        /// </summary>
        public static string NoStudentsToAssign {
            get {
                return ResourceManager.GetString("NoStudentsToAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No teacher assigned.
        /// </summary>
        public static string NoTeacherAssigned {
            get {
                return ResourceManager.GetString("NoTeacherAssigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1}.
        /// </summary>
        public static string PersonFullNameFormat {
            get {
                return ResourceManager.GetString("PersonFullNameFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} - {1} {2}.
        /// </summary>
        public static string PersonToStringFormat {
            get {
                return ResourceManager.GetString("PersonToStringFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Id of the student, to whom you want to assign the teacher.
        /// </summary>
        public static string PickStudentToAssign {
            get {
                return ResourceManager.GetString("PickStudentToAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Id of the student, whom you want to delete.
        /// </summary>
        public static string PickStudentToDelete {
            get {
                return ResourceManager.GetString("PickStudentToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Id of the student, whom you want to revoke from the teacher.
        /// </summary>
        public static string PickStudentToRevoke {
            get {
                return ResourceManager.GetString("PickStudentToRevoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Id of the student who you want to update.
        /// </summary>
        public static string PickStudentToUpdate {
            get {
                return ResourceManager.GetString("PickStudentToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Id of the teacher, whom you want to assign to a student.
        /// </summary>
        public static string PickTeacherToAssign {
            get {
                return ResourceManager.GetString("PickTeacherToAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Id of the teacher, whom you want to delete.
        /// </summary>
        public static string PickTeacherToDelete {
            get {
                return ResourceManager.GetString("PickTeacherToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Id of the teacher, whom you want to revoke.
        /// </summary>
        public static string PickTeacherToRevoke {
            get {
                return ResourceManager.GetString("PickTeacherToRevoke", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Id of the teacher who you want to update.
        /// </summary>
        public static string PickTeacherToUpdate {
            get {
                return ResourceManager.GetString("PickTeacherToUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to save changes. The entity was deleted by another user.
        /// </summary>
        public static string UnableSaveChanges {
            get {
                return ResourceManager.GetString("UnableSaveChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong Id. Please try again.
        /// </summary>
        public static string WrongId {
            get {
                return ResourceManager.GetString("WrongId", resourceCulture);
            }
        }
    }
}
