USE [master]
GO

/****** Object:  Database [BooksShop]    Script Date: 19.01.2017 15:18:33 ******/
CREATE DATABASE [BooksShop]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BooksShop', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\BooksShop.mdf' , SIZE = 4288KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'BooksShop_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL12.SQLEXPRESS\MSSQL\DATA\BooksShop_log.ldf' , SIZE = 1072KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [BooksShop] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BooksShop].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BooksShop] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BooksShop] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BooksShop] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BooksShop] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BooksShop] SET ARITHABORT OFF 
GO

ALTER DATABASE [BooksShop] SET AUTO_CLOSE ON 
GO

ALTER DATABASE [BooksShop] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BooksShop] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BooksShop] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BooksShop] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BooksShop] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BooksShop] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BooksShop] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BooksShop] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BooksShop] SET  ENABLE_BROKER 
GO

ALTER DATABASE [BooksShop] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BooksShop] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BooksShop] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BooksShop] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BooksShop] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BooksShop] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [BooksShop] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BooksShop] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [BooksShop] SET  MULTI_USER 
GO

ALTER DATABASE [BooksShop] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BooksShop] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BooksShop] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BooksShop] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [BooksShop] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [BooksShop] SET  READ_WRITE 
GO

